@startuml
class com.mygdx.platventure.EcouteurContacts {
- Body joyauSupprime
- boolean joyauTouche
- boolean persoEstMort
- boolean contactBriqueOuPlateforme
- boolean sortieDepassee
+ void beginContact(Contact)
+ void endContact(Contact)
+ void preSolve(Contact,Manifold)
+ void postSolve(Contact,ContactImpulse)
+ Body getJoyauSupprime()
+ boolean isJoyauTouche()
+ boolean isPersoEstMort()
+ void setJoyauTouche(boolean)
+ boolean isSortieDepassee()
+ void dispose()
+ boolean isContactBriqueOuPlateforme()
+ void setContactBriqueOuPlateforme(boolean)
}
class com.mygdx.platventure.elements.Personnage {
- PolygonShape formeHaut
- CircleShape formeBas
- float densite
- float restitution
- float friction
- boolean saute
+ void setBodyDef()
+ void setFixture()
# void setUserData()
+ void appliquerMouvement(Vector2)
+ float getLargeur()
+ float getHauteur()
+ void dispose()
+ void setTextureCourse()
+ void setTextureSaut()
+ void setTextureIdle()
}
class com.mygdx.platventure.elements.elementsTraversables.Joyau {
- CircleShape forme
- int num_joyau
- Animation animation
+ void setBodyDef()
+ void setFixture()
# void setUserData()
+ int getScore()
+ float getLargeur()
+ float getHauteur()
+ void dispose()
+ Animation getAnimation()
}
abstract class com.mygdx.platventure.elements.ElementGraphique {
# Vector2 pos
# Body body
# BodyDef bodyDef
# Texture texture
+ {abstract}void setBodyDef()
+ {abstract}void setFixture()
+ void createBody(World)
# {abstract}void setUserData()
+ Vector2 getPos()
+ void setPos(Vector2)
+ Body getBody()
+ void setBody(Body)
+ BodyDef getBodyDef()
+ void setBodyDef(BodyDef)
+ {abstract}void dispose()
+ Texture getTexture()
+ {abstract}float getLargeur()
+ {abstract}float getHauteur()
}
class com.mygdx.platventure.elements.Brique {
- PolygonShape forme
- float densite
- float restitution
- float friction
+ void setBodyDef()
+ void setFixture()
# void setUserData()
+ float getLargeur()
+ float getHauteur()
+ void dispose()
}
class com.mygdx.platventure.EcouteurUtilisateur {
- Vector2 mouvement
- boolean ajoutTimer
- boolean mettreEnPause
+ boolean keyDown(int)
+ boolean keyUp(int)
+ boolean keyTyped(char)
+ boolean touchDown(int,int,int,int)
+ boolean touchUp(int,int,int,int)
+ boolean touchDragged(int,int,int)
+ boolean mouseMoved(int,int)
+ boolean scrolled(float,float)
+ Vector2 getMouvement()
+ boolean isAjoutTimer()
+ void setAjoutTimer(boolean)
+ boolean isMettreEnPause()
}
class com.mygdx.platventure.ecrans.EcranJeu {
- PlatVenture platVenture
- Texture fond
- OrthographicCamera camera
- OrthographicCamera cameraTexte
- FitViewport vp
- Monde monde
- EcouteurUtilisateur ecouteurUtilisateur
- BitmapFont font
- int indexAnimationJoyau
- float tempsDepuisDerniereAnimationJoyau
+ void show()
+ void render(float)
+ void resize(int,int)
+ void ajusterCameraSurPersonnage()
+ void ajusterCameraNiveau3()
- void chargerFont()
}
class com.mygdx.platventure.Monde {
- ArrayList<ElementGraphique> elements
- World world
- Personnage personnage
- EcouteurContacts ecouteurContacts
- int score_joueur
- int largeur_niveau
- int hauteur_niveau
- Niveau niveau
- Timer timer
- int numNiveau
- int[] timer_limite
- boolean[] pause
- Vector2 posPersoInit
- boolean gagne
- boolean perdu
- Timer timerAlerte
- boolean niveau3
- Sound son_joyau
- Sound son_eau
- Sound son_danger
- Sound son_collision
- Sound son_perdu
- Sound son_gagne
- void creerMonde()
- ElementGraphique creerElementDansMonde(char,int,int,int)
+ World getWorld()
+ Personnage getPersonnage()
+ void update()
- void relancerMonde(float)
- void lancerProchainMonde()
+ Niveau getNiveau()
+ void dispose()
+ Vector2 getPosPersoInit()
+ int getScore_joueur()
+ int getTimer_limite()
+ boolean isGagne()
+ boolean isPerdu()
+ ArrayList<ElementGraphique> getElements()
+ void ajoutTimer()
+ void changerPause(boolean)
+ boolean isNiveau3()
}
class com.mygdx.platventure.elements.plateformes.PlateformeBordGauche {
- PolygonShape forme
- float densite
- float restitution
- float friction
+ void setBodyDef()
+ void setFixture()
# void setUserData()
+ float getLargeur()
+ float getHauteur()
+ void dispose()
}
class com.mygdx.platventure.PlatVenture {
- SpriteBatch batch
+ void create()
+ void dispose()
+ SpriteBatch getBatch()
}
class com.mygdx.platventure.elements.plateformes.PlateformeCentrale {
- PolygonShape forme
- float densite
- float restitution
- float friction
+ void setBodyDef()
+ void setFixture()
# void setUserData()
+ float getLargeur()
+ float getHauteur()
+ void dispose()
}
class com.mygdx.platventure.ecrans.EcranPresentation {
- PlatVenture platVenture
- Texture fond
+ void show()
+ void render(float)
+ void hide()
}
class com.mygdx.platventure.Niveau {
- int larg
- int haut
- int temps
- char[][] tab_char
- String nom_fond
+ int getLarg()
+ int getHaut()
+ int getTemps()
+ char[][] getTab_char()
+ String getNom_fond()
+ void dispose()
}
class com.mygdx.platventure.elements.elementsTraversables.Sortie {
- PolygonShape forme
+ void setBodyDef()
+ void setFixture()
# void setUserData()
+ float getLargeur()
+ float getHauteur()
+ void dispose()
}
class com.mygdx.platventure.elements.elementsTraversables.Eau {
- PolygonShape forme
+ void setBodyDef()
+ void setFixture()
# void setUserData()
+ float getLargeur()
+ float getHauteur()
+ void dispose()
}
class com.mygdx.platventure.elements.plateformes.PlateformeBordDroit {
- PolygonShape forme
- float densite
- float restitution
- float friction
+ void setBodyDef()
+ void setFixture()
# void setUserData()
+ float getLargeur()
+ float getHauteur()
+ void dispose()
}


com.mygdx.platventure.ContactListener <|.. com.mygdx.platventure.EcouteurContacts
com.mygdx.platventure.elements.ElementGraphique <|-- com.mygdx.platventure.elements.Personnage
com.mygdx.platventure.elements.ElementGraphique <|-- com.mygdx.platventure.elements.elementsTraversables.Joyau
com.mygdx.platventure.elements.ElementGraphique <|-- com.mygdx.platventure.elements.Brique
com.badlogic.gdx.InputProcessor <|.. com.mygdx.platventure.EcouteurUtilisateur
com.badlogic.gdx.ScreenAdapter <|-- com.mygdx.platventure.ecrans.EcranJeu
com.mygdx.platventure.elements.ElementGraphique <|-- com.mygdx.platventure.elements.plateformes.PlateformeBordGauche
com.badlogic.gdx.Game <|-- com.mygdx.platventure.PlatVenture
com.mygdx.platventure.elements.ElementGraphique <|-- com.mygdx.platventure.elements.plateformes.PlateformeCentrale
com.badlogic.gdx.ScreenAdapter <|-- com.mygdx.platventure.ecrans.EcranPresentation
com.mygdx.platventure.elements.ElementGraphique <|-- com.mygdx.platventure.elements.elementsTraversables.Sortie
com.mygdx.platventure.elements.ElementGraphique <|-- com.mygdx.platventure.elements.elementsTraversables.Eau
com.mygdx.platventure.elements.ElementGraphique <|-- com.mygdx.platventure.elements.plateformes.PlateformeBordDroit
@enduml